### ISSUE TITLE
Omniauth

### ISSUE THREAD

**Issue by maletor** [doximity/doximity-auth#6]
Is there a distinct advantage to building this versus using an existing gem?

If so, does it outweigh the advantages of [becoming an extension](https://github.com/intridea/omniauth/wiki/List-of-Strategies) for [a widely used OAuth client](https://github.com/intridea/omniauth)?

Combining [Devise with OmniAuth](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview) work well, even for internal applications, and eliminates the need to maintain this dependency.

**Comment by jeyb** [comment]
I have a feeling there are things we do that won't fit nicely into the OmniAuth model. It probably could be molded to fit but I don't see huge benefits. Our current partners use OAuth libraries of their choice and it's fine for them. If there were clients who requested a Ruby OmniAuth extension and it provides value to our business to do so, then I'd be for it.

That being said, I'll let @divoxx answer more thoroughly since he made the design decisions here. /cc @brupm

**Comment by divoxx** [comment]
This gem does not do the same thing as omni auth can do, this is not an OAuth client. 

If you look at what the [roles are on OAuth](https://tools.ietf.org/html/rfc6749#section-1.1), you'll notice the existence of an Resource Server, which is basically how do we protect resources of a same domain under the same authorizations server. It's for authenticating/authorizing the serving of resources, not consuming resources.

Our apps are both resource servers and clients. When they need to perform actions as a client, they will use oauth2 gem, we're not duplicating that.

This gem takes care of two things:

1. Shared session, properly reading, decrypting and validating a token against the authorization server;
2. A standard, integrated way to protect resources using shared session or OAuth2 for whoever client is consuming.

Hope this clarifies it.
